baseurl = "http://leemorris.co.uk"
languageCode = "en-gb"
title = "Lee Morris"

paginate = 10
theme = "cactus-theme"

[params]
    name = "Lee Morris"
    description = "Software Engineer, Bucks UK"
    bio = "Software Developer, Bucks UK"
    enableRSS = true
    github = "leemorrisdev"
    ga_api_key = "UA-42836201-1"
    avatar = "../../static/img/avatar.png"
